# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
java = "21"
kotlin = "2.1.10"
kotlinxDatetime = "0.6.1"
kotlinxSerializationJSON = "1.7.2"
kotlinxCoroutines = "1.8.1"
springBoot = "3.4.3"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

# Spring
spring-boot-starter-amqp = { module = "org.springframework.boot:spring-boot-starter-amqp" }

# Jackson
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin"}
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core"}
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind"}
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations"}
jackson-datatype = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310"}

# Plugins dependencies for buildSrc
kotlinJvmPlugin = { module = "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }
kotlinSpringPlugin = { module = "org.jetbrains.kotlin.plugin.spring:org.jetbrains.kotlin.plugin.spring.gradle.plugin", version.ref = "kotlin" }
springBootPlugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "springBoot" }

# Libraries can be bundled together for easier import
[bundles]
kotlinxEcosystem = [ "kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines" ]
jacksons = [ "jackson-core", "jackson-databind", "jackson-annotations", "jackson-datatype" ]

[plugins]
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }